# Generated by Django 5.1.7 on 2025-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('active', 'active'), ('missed', 'missed')], default='active', max_length=20)),
                ('days_left', models.IntegerField(editable=False)),
                ('priority', models.IntegerField(default=1, editable=False)),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
    ]
